/* Declaration of MyPair, which resembles std::pair
 * Use this as the element to store in your TreeNode.
 * Do not edit this file.
 * After this assignment (e.g., pa07 and beyond) you can use std::pair
 * https://en.cppreference.com/w/cpp/utility/pair
 */

#ifndef MYPAIR_H
#define MYPAIR_H

template <typename K, typename V> 
struct MyPair
{
    K first; 
    V second;
    
    MyPair(){}
    MyPair(const K &key): first(key) {}
    MyPair(const K &key, const V &value): first(key), second(value) {}
};

#endif

